# Generated by Django 5.1.1 on 2024-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='message',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='msg',
            name='mob',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='msg',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
